version: 2.1
orbs:
  node: circleci/node@4.1

parameters:
  run-api:
    type: boolean
    default: false
  run-client:
    type: boolean
    default: false
  run-dashboard:
    type: boolean
    default: false

jobs:
  deploy-client:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Prepare Env
          command: |
            yarn global add vercel
            echo 'export VERCEL_PROJECT_ID="$CLIENT_PROJECT_ID"' >> "$BASH_ENV"
      - run:
          name: Vercel Pull
          command: vercel pull --environment=preview -y -t $VERCEL_TOKEN
      - run:
          name: Vercel Build
          command: vercel build -t $VERCEL_TOKEN
      - run:
          name: Vercel Deploy
          command: echo "export VERCEL_URL=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> "$BASH_ENV"
      - run:
          name: Set alias
          command: |
            vercel alias set $VERCEL_URL client-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM.vercel.app --scope lettercms -t $VERCEL_TOKEN
            vercel alias set $VERCEL_URL lettercms-client-$CIRCLE_BRANCH.vercel.app --scope lettercms -t $VERCEL_TOKEN

  deploy-dashboard:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Prepare Env
          command: |
            yarn global add vercel
            echo 'export VERCEL_PROJECT_ID="$DASHBOARD_PROJECT_ID"' >> "$BASH_ENV"
            echo 'export NEXTAUTH_URL="https://lettercms-dashboard-$CIRCLE_BRANCH.vercel.app"' >> "$BASH_ENV"
      - run:
          name: Vercel Pull
          command: vercel pull --environment=preview -y -t $VERCEL_TOKEN
      - run:
          name: Vercel Build
          command: vercel build -t $VERCEL_TOKEN
      - run:
          name: Vercel Deploy
          command: echo "export VERCEL_URL=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> "$BASH_ENV"
      - run:
          name: Set alias
          command: |
            vercel alias set $VERCEL_URL dashboard-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM.vercel.app --scope lettercms -t $VERCEL_TOKEN
            vercel alias set $VERCEL_URL lettercms-dashboard-$CIRCLE_BRANCH.vercel.app --scope lettercms -t $VERCEL_TOKEN

  deploy-api:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Prepare Env
          command: |
            yarn global add vercel
            echo 'export VERCEL_PROJECT_ID="$API_PROJECT_ID"' >> "$BASH_ENV"
      - run:
          name: Vercel Pull
          command: vercel pull --environment=preview -y -t $VERCEL_TOKEN
      - run:
          name: Vercel Build
          command: vercel build -t $VERCEL_TOKEN
      - run:
          name: Vercel Deploy
          command: echo "export VERCEL_URL=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> "$BASH_ENV"
      - run:
          name: Set alias
          command: |
            vercel alias set $VERCEL_URL api-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM.vercel.app --scope lettercms -t $VERCEL_TOKEN
            vercel alias set $VERCEL_URL lettercms-api-$CIRCLE_BRANCH.vercel.app --scope lettercms -t $VERCEL_TOKEN

workflows:
  api-preview:
    when: << pipeline.parameters.run-api >>
    jobs:
      - deploy-api:
          context:
            - LetterCMS
  client-preview:
    when: << pipeline.parameters.run-client >>
    jobs:
      - deploy-client:
          context:
            - LetterCMS
  dashboard-preview:
    when: << pipeline.parameters.run-dashboard >>
    jobs:
      - deploy-dashboard:
          context:
            - LetterCMS
