name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: preview

    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
 
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
 
      - name: Install dependencies
        run: yarn
 
      - name: Build
        run: yarn build
 
      - name: Test
        run: yarn deploy
