name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FB_APP_ID: ${{ secrets.FB_APP_ID }}
  FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
  FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
  JWT_AUTH: ${{ secrets.JWT_AUTH }}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
  UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}


jobs:
  deploy-api:
    environment:
      name: preview/api
      url: https://lettercms-api-${{ github.ref_name }}.vercel.app
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      PAYPAL_PRODUCTION_CLIENT: ${{ secrets.PAYPAL_PRODUCTION_CLIENT }}
      PAYPAL_PRODUCTION_SECRET: ${{ secrets.PAYPAL_PRODUCTION_SECRET }}
      VERCEL_PROJECT_ID: ${{secrets.API_PROJECT_ID}}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./apps/api/.next/cache
          key: lettercms-api-cache

      - name: Vercel Pull
        run: vercel pull --environment=preview -y -t $VERCEL_TOKEN
      
      - name: Vercel Build 
        run: vercel  build -t $VERCEL_TOKEN

      - name: Vercel Deploy
        run: echo "vercel_url=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> $GITHUB_ENV

      - name: Set alias
        run: vercel alias set ${{ env.vercel_url }} lettercms-api-${{ github.ref_name }}.vercel.app --scope lettercms -t $VERCEL_TOKEN

      - uses: actions/cache@v3
        with:
          path: ./apps/api/.next/cache
          key: lettercms-api-cache

  deploy-client:
    environment:
      name: preview/client
      url: https://lettercms-client-${{ github.ref_name }}.vercel.app
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      PAYPAL_PRODUCTION_CLIENT: ${{ secrets.PAYPAL_PRODUCTION_CLIENT }}
      PAYPAL_PRODUCTION_SECRET: ${{ secrets.PAYPAL_PRODUCTION_SECRET }}
      VERCEL_PROJECT_ID: ${{secrets.CLIENT_PROJECT_ID}}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./apps/client/.next/cache
          key: lettercms-client-cache

      - name: Vercel Pull
        run: vercel pull --environment=preview -y -t $VERCEL_TOKEN

      - name: Build SDK
        run: yarn workspace @lettercms/sdk --verbose build

      - name: Vercel Build 
        run: vercel  build -t $VERCEL_TOKEN

      - name: Vercel Deploy
        run: echo "vercel_url=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> $GITHUB_ENV

      - name: Set alias
        run: vercel alias set ${{ env.vercel_url }} lettercms-client-${{ github.ref_name }}.vercel.app --scope lettercms -t $VERCEL_TOKEN

      - uses: actions/cache@v3
        with:
          path: ./apps/client/.next/cache
          key: lettercms-client-cache

  deploy-dashboard:
    environment:
      name: preview/dashboard
      url: https://lettercms-dashboard-${{ github.ref_name }}.vercel.app
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      PAYPAL_PRODUCTION_CLIENT: ${{ secrets.PAYPAL_PRODUCTION_CLIENT }}
      PAYPAL_PRODUCTION_SECRET: ${{ secrets.PAYPAL_PRODUCTION_SECRET }}
      VERCEL_PROJECT_ID: ${{secrets.DASHBOARD_PROJECT_ID}}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./apps/dashboard/.next/cache
          key: lettercms-dashboard-cache

      - name: Vercel Pull
        run: vercel pull --environment=preview -y -t $VERCEL_TOKEN

      - name: Build SDK
        run: yarn workspace @lettercms/sdk --verbose build
      
      - name: Vercel Build 
        run: vercel  build -t $VERCEL_TOKEN

      - name: Vercel Deploy
        run: echo "vercel_url=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> $GITHUB_ENV

      - name: Set alias
        run: vercel alias set ${{ env.vercel_url }} lettercms-dashboard-${{ github.ref_name }}.vercel.app --scope lettercms -t $VERCEL_TOKEN

      - uses: actions/cache@v3
        with:
          path: ./apps/dashboard/.next/cache
          key: lettercms-dashboard-cache
