name: Build and Deploy

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string  
      env:
        required: true
        type: string


env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FB_APP_ID: ${{ secrets.FB_APP_ID }}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}


jobs:
  deploy:
    environment:
      name: ${{github.event.inputs.env}}/${{github.event.inputs.name}}
      url: https://${{env.env_url}}
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      PAYPAL_PRODUCTION_CLIENT: ${{ secrets.PAYPAL_PRODUCTION_CLIENT }}
      PAYPAL_PRODUCTION_SECRET: ${{ secrets.PAYPAL_PRODUCTION_SECRET }}
      VERCEL_PROJECT_ID: ${{secrets.API_PROJECT_ID}}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./apps/${{github.event.inputs.name}}/.next/cache
          key: lettercms-${{github.ref_name}}-${{github.event.inputs.name}}-${{hashFiles('yarn.lock')}}
          restore-keys: |
            lettercms-${{github.ref_name}}-${{github.event.inputs.name}}-
            lettercms-${{github.ref_name}}-
            lettercms-

      - name: Vercel Pull 
        run: vercel pull --environment=${{github.event.inputs.env}} -y -t $VERCEL_TOKEN
      
      - name: Vercel Build Preview
        if: ${{github.event.inputs.env == 'preview'}}
        run: vercel build -t $VERCEL_TOKEN

      - name: Vercel Build Production
        if: ${{github.event.inputs.env == 'production'}}
        run: vercel build --prod -t $VERCEL_TOKEN

      - name: Vercel Deploy Preview
        if: ${{github.event.inputs.env == 'preview'}}
        run: echo "vercel_url=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> $GITHUB_ENV
      
      - name: Vercel Deploy Production
        if: ${{github.event.inputs.env == 'production'}}
        run: echo "vercel_url=$(vercel --prebuilt --prod -t $VERCEL_TOKEN)" >> $GITHUB_ENV

      - name: 'Generate Preview URL'
        if: ${{github.event.inputs.env == 'preview'}}
        run: echo "env_url=${{github.event.inputs.name}}-${{ github.ref_name }}-$(git rev-parse --short HEAD).vercel.app >> $GITHUB_ENV

      - name: 'Generate API Production URL'
        if: ${{github.event.inputs.env == 'production' && github.event.inputs.name == 'api'}}
        run: echo "env_url=api.lettercms.vercel.app" >> $GITHUB_ENV

      - name: 'Generate Dashboard Production URL'
        if: ${{github.event.inputs.env == 'production' && github.event.inputs.name == 'dashboard'}}
        run: echo "env_url=lettercms.vercel.app" >> $GITHUB_ENV

      - name: 'Generate Client Production URL'
        if: ${{github.event.inputs.env == 'production'}}
        run: echo "env_url=davidsdevel.lettercms.vercel.app" >> $GITHUB_ENV

      - name: Set alias
        if: ${{github.event.inputs.env == 'preview'}}
        run: vercel alias set ${{ env.vercel_url }} ${{env.env_url}} --scope lettercms -t $VERCEL_TOKEN
      
      - uses: actions/cache@v3
        with:
          path: ./apps/${{github.event.inputs.name}}/.next/cache
          key: lettercms-${{github.event.inputs.name}}-cache
