on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      env:
        required: true
        type: string
      vercel_env:
        required: true
        type: string


concurrency:
  group: ci-${{ inputs.env }}-${{ inputs.name }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FB_APP_ID: ${{ secrets.FB_APP_ID }}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}

jobs:
  deploy:
    environment:
      name: ${{inputs.env}}
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      PAYPAL_PRODUCTION_CLIENT: ${{ secrets.PAYPAL_PRODUCTION_CLIENT }}
      PAYPAL_PRODUCTION_SECRET: ${{ secrets.PAYPAL_PRODUCTION_SECRET }}
      NEXTAUTH_URL: https://lettercms-${{inputs.name}}-${{github.ref_name}}.vercel.app

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./apps/${{inputs.name}}/.next/cache
          key: lettercms-${{github.ref_name}}-${{inputs.name}}-${{hashFiles('yarn.lock')}}
          restore-keys: |
            lettercms-${{github.ref_name}}-${{inputs.name}}-
            lettercms-${{github.ref_name}}-
            lettercms-

      - name: Define Vercel API ID to env 
        if: ${{inputs.name == 'api'}}
        run: echo "VERCEL_PROJECT_ID=${{secrets.API_PROJECT_ID}}" >> $GITHUB_ENV


      - name: Define Vercel Client ID to env 
        if: ${{inputs.name == 'client'}}
        run: echo "VERCEL_PROJECT_ID=${{secrets.CLIENT_PROJECT_ID}}" >> $GITHUB_ENV

      - name: Define Vercel Dashboard ID to env 
        if: ${{inputs.name == 'dashboard'}}
        run: echo "VERCEL_PROJECT_ID=${{secrets.DASHBOARD_PROJECT_ID}}" >> $GITHUB_ENV

      - name: Vercel Pull 
        run: vercel pull --environment=${{inputs.vercel_env}} -y -t $VERCEL_TOKEN
      
      - name: Vercel Build Preview
        if: ${{inputs.env == 'staging'}}
        run: vercel build -t $VERCEL_TOKEN

      - name: Vercel Build Production
        if: ${{inputs.env == 'production'}}
        run: vercel build --prod -t $VERCEL_TOKEN


      - name: Vercel Deploy Preview
        if: ${{inputs.env == 'staging'}}
        run: echo "vercel_url=$(vercel --prebuilt -t $VERCEL_TOKEN)" >> $GITHUB_ENV
      
      - name: Vercel Deploy Production
        if: ${{inputs.env == 'production'}}
        run: echo "vercel_url=$(vercel --prebuilt --prod -t $VERCEL_TOKEN)" >> $GITHUB_ENV


      - name: 'Generate Client Staging URL'
        if: ${{inputs.env == 'staging' && inputs.name == 'client'}}
        run: echo "env_url=davidsdevel.lettercms.vercel.app" >> $GITHUB_ENV

      - name: 'Generate Dashboard Staging URL'
        if: ${{inputs.env == 'staging' && inputs.name == 'dashboard'}}
        run: echo "env_url=lettercms-preview.vercel.app" >> $GITHUB_ENV

      - name: 'Generate API Staging URL'
        if: ${{inputs.env == 'staging' && inputs.name == 'api'}}
        run: echo "env_url=lettercms-api-main.vercel.app" >> $GITHUB_ENV


      - name: 'Generate API Production URL'
        if: ${{inputs.env == 'production' && inputs.name == 'api'}}
        run: echo "env_url=api.lettercms.vercel.app" >> $GITHUB_ENV

      - name: 'Generate Dashboard Production URL'
        if: ${{inputs.env == 'production' && inputs.name == 'dashboard'}}
        run: echo "env_url=lettercms.vercel.app" >> $GITHUB_ENV

      - name: 'Generate Client Production URL'
        if: ${{inputs.env == 'production' && inputs.name == 'client'}}
        run: echo "env_url=*.lettercms.vercel.app" >> $GITHUB_ENV


      - name: Set alias
        if: ${{inputs.env == 'staging'}}
        run: vercel alias set ${{env.vercel_url}} ${{env.env_url}} --scope lettercms -t $VERCEL_TOKEN
