name: Promote to Production

on:
  push:
    branches:
      - production

jobs:
  deploy-api:
    uses: ./.github/workflows/deploy.yml
    with:
      name: api
      env: production
      vercel_env: production
    secrets: inherit

  deploy-client:
    uses: ./.github/workflows/deploy.yml
    with:
      name: client
      env: production
      vercel_env: production
    secrets: inherit

  deploy-dashboard:
    uses: ./.github/workflows/deploy.yml
    with:
      name: dashboard
      env: production
      vercel_env: production
    secrets: inherit
